-- Migración independiente: configuración de máquinas termográficas
-- Ejecutar en Supabase > SQL Editor.

create table if not exists public."tbTermoConfiguracion" (
  "Id" bigint generated by default as identity primary key,
  "Grupo" text not null,
  "Maquina" text not null,
  "Componente" text not null,
  "LimiteNormal" numeric,
  "LimiteAlerta" numeric,
  "LimitePeligro" numeric,
  "ImagenRequerida" boolean not null default false,
  "Activo" boolean not null default true,
  "created_at" timestamptz not null default now(),
  "updated_at" timestamptz not null default now()
);

-- Asegura que no se repita el mismo componente dentro de una máquina.
create unique index if not exists "uq_termo_maquina_componente"
  on public."tbTermoConfiguracion" ("Maquina", "Componente");

create index if not exists "idx_termo_config_grupo"
  on public."tbTermoConfiguracion" ("Grupo", "Maquina");

alter table public."tbTermoConfiguracion" enable row level security;

-- No se crea una política pública. La API de Vercel accede con service_role.

-- Datos iniciales opcionales. Se conservan los existentes.
insert into public."tbTermoConfiguracion"
  ("Grupo","Maquina","Componente","LimiteNormal","LimiteAlerta","LimitePeligro","ImagenRequerida")
values
  ('Taller Central','TC04','Motor',55,70,85,true),
  ('Taller Central','TC04','Rodamiento',60,75,90,true),
  ('Taller Central','TC05','Tablero eléctrico',50,65,80,true),
  ('Producción','PR01','Bomba',55,70,82,true),
  ('Producción','PR01','Acoplamiento',50,65,78,false),
  ('Producción','PR02','Reductor',65,80,95,true)
on conflict ("Maquina","Componente") do nothing;

-- Fuerza a PostgREST a recargar el esquema inmediatamente.
notify pgrst, 'reload schema';
