-- STB Monitor Termografico - esquema inicial para Supabase
-- Ejecutar completo en SQL Editor. Los nombres usan el estilo de STB-Predictivo.

create table if not exists public."tbUsuarios" (
  "Codigo" text primary key,
  "Nombre" text not null,
  "Rol" text not null check (lower("Rol") in ('tecnico','técnico','supervisor','administrador','admin','jefe')),
  "Contrasena" text not null,
  "Grupo" text not null default 'Todos',
  "Activo" text not null default 'TRUE',
  "created_at" timestamptz not null default now(),
  "updated_at" timestamptz not null default now()
);

create table if not exists public."tbTermoConfiguracion" (
  "Id" bigint generated by default as identity primary key,
  "Grupo" text not null,
  "Maquina" text not null,
  "Componente" text not null,
  "LimiteNormal" numeric,
  "LimiteAlerta" numeric,
  "LimitePeligro" numeric,
  "ImagenRequerida" boolean not null default false,
  "Activo" boolean not null default true,
  "created_at" timestamptz not null default now(),
  "updated_at" timestamptz not null default now(),
  unique ("Maquina", "Componente")
);

create table if not exists public."tbTermoPaletas" (
  "Paleta" text primary key,
  "TemperaturaMinima" numeric not null,
  "TemperaturaMaxima" numeric not null,
  "Emisividad" numeric not null default 0.95,
  "Distancia" numeric not null default 1,
  "Activo" boolean not null default true,
  "updated_at" timestamptz not null default now()
);

create table if not exists public."tbTermoInspecciones" (
  "Id" uuid primary key default gen_random_uuid(),
  "Fecha" date not null default current_date,
  "Semana" integer not null,
  "NroOrden" text default '',
  "Grupo" text not null,
  "Maquina" text not null,
  "Componente" text not null,
  "Conformidad" text not null check ("Conformidad" in ('Sí','No')),
  "Temperatura" numeric,
  "Observacion" text default '',
  "AgregaraImagen" boolean not null default false,
  "InspectorCodigo" text references public."tbUsuarios"("Codigo"),
  "Inspector" text not null,
  "Criticidad" text not null default 'Sin evaluar',
  "Estado" text not null default 'Cerrada',
  "Paleta" text default '',
  "TemperaturaMinima" numeric,
  "TemperaturaMaxima" numeric,
  "TemperaturaPunto" numeric,
  "DiferenciaT" numeric,
  "Emisividad" numeric,
  "Distancia" numeric,
  "ObservacionTecnica" text default '',
  "Conclusion" text default '',
  "AccionTomada" text default '',
  "CerradoPor" text default '',
  "FechaCierre" timestamptz,
  "created_at" timestamptz not null default now(),
  "updated_at" timestamptz not null default now()
);

create table if not exists public."tbTermoImagenes" (
  "Id" uuid primary key default gen_random_uuid(),
  "InspeccionId" uuid not null references public."tbTermoInspecciones"("Id") on delete restrict,
  "StoragePath" text not null,
  "NombreArchivo" text not null,
  "MimeType" text default 'image/jpeg',
  "Tamano" bigint,
  "Activo" boolean not null default true,
  "CargadoPor" text not null,
  "created_at" timestamptz not null default now()
);

create table if not exists public."tbTermoAuditoria" (
  "Id" bigint generated by default as identity primary key,
  "InspeccionId" uuid references public."tbTermoInspecciones"("Id") on delete restrict,
  "UsuarioCodigo" text,
  "Usuario" text not null,
  "Rol" text not null,
  "Accion" text not null,
  "ValorAnterior" jsonb,
  "ValorNuevo" jsonb,
  "Motivo" text default '',
  "created_at" timestamptz not null default now()
);

create index if not exists "idx_termo_estado" on public."tbTermoInspecciones" ("Estado");
create index if not exists "idx_termo_fecha" on public."tbTermoInspecciones" ("Fecha" desc);
create index if not exists "idx_termo_maquina" on public."tbTermoInspecciones" ("Maquina", "Componente");
create index if not exists "idx_termo_imagen_inspeccion" on public."tbTermoImagenes" ("InspeccionId");
create index if not exists "idx_termo_auditoria_inspeccion" on public."tbTermoAuditoria" ("InspeccionId", "created_at" desc);

alter table public."tbUsuarios" enable row level security;
alter table public."tbTermoConfiguracion" enable row level security;
alter table public."tbTermoPaletas" enable row level security;
alter table public."tbTermoInspecciones" enable row level security;
alter table public."tbTermoImagenes" enable row level security;
alter table public."tbTermoAuditoria" enable row level security;

-- Bucket privado. La API de Vercel accede con service_role.
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('termografias', 'termografias', false, 10485760, array['image/jpeg','image/png','image/webp'])
on conflict (id) do update set public=false;

insert into public."tbUsuarios" ("Codigo","Nombre","Rol","Contrasena","Grupo","Activo") values
('10000001','Julio Senisse','tecnico','1234','Todos','TRUE'),
('10000002','Gustavo Flores','supervisor','1234','Todos','TRUE'),
('10000003','JKenyo Villegas','administrador','1234','Todos','TRUE'),
('10000004','Robertho Espinoza','jefe','1234','Todos','TRUE')
on conflict ("Codigo") do update set "Nombre"=excluded."Nombre", "Rol"=excluded."Rol", "Grupo"=excluded."Grupo", "Activo"=excluded."Activo";

insert into public."tbTermoConfiguracion" ("Grupo","Maquina","Componente","LimiteNormal","LimiteAlerta","LimitePeligro","ImagenRequerida") values
('Taller Central','TC04','Motor',55,70,85,true),
('Taller Central','TC04','Rodamiento',60,75,90,true),
('Taller Central','TC05','Tablero eléctrico',50,65,80,true),
('Producción','PR01','Bomba',55,70,82,true),
('Producción','PR01','Acoplamiento',50,65,78,false),
('Producción','PR02','Reductor',65,80,95,true)
on conflict ("Maquina","Componente") do nothing;

insert into public."tbTermoPaletas" ("Paleta","TemperaturaMinima","TemperaturaMaxima","Emisividad","Distancia") values
('Hierro',20,120,0.95,1),('Arcoíris',20,150,0.95,1),('Blanco caliente',15,100,0.95,1),
('Negro caliente',15,100,0.95,1),('Escala de grises',20,120,0.95,1),('Otra',20,100,0.95,1)
on conflict ("Paleta") do nothing;

-- No se crean políticas para anon/authenticated: el frontend no accede directamente.
-- La API serverless usa service_role y omite RLS de forma segura.
